
name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy Web App to Vercel
        run: npm run deploy --workspace=apps/web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  # For the Go API, consider deploying to platforms like Render or Fly.io.
  # This example does not include direct deployment for Go, as it's outside Vercel's primary scope.
  # You would typically set up a separate CI/CD pipeline for your Go application.
